spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/somaeja?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
    username: lob
    password: eodend101@@
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  mapper-locations: main.resources.mybatis.mapper

logging:
  level:

    root:
      level: debug
      additivity: false

    com:
      somaeja:
        post:
          service:
            PostService:
              level: info
              additivity: false

        global:
          exception:
            GlobalExceptionHandler:
              level: error
              additivity: false

  file:
    path: /logs/somaeja

  pattern:
    dateformat: yyyy-MM-dd HH:mm:ss
