spring:
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true

mybatis:
  mapper-locations: main.resources.mybatis.mapper
