DROP TABLE IF EXISTS POST CASCADE;
DROP TABLE IF EXISTS LOCATION CASCADE;

CREATE TABLE POST
(
    POST_ID        INTEGER PRIMARY KEY auto_increment,
    USER_ID        INTEGER      NOT NULL,
    LOCATION_ID    INTEGER      NOT NULL,
    IMAGE_ID       INTEGER      NOT NULL,
    TITLE          VARCHAR(255) NOT NULL,
    CONTENT        VARCHAR(255) NOT NULL,
    PRICE          VARCHAR(255) NOT NULL,
    IS_NEGOTIABLE  TINYINT(1)   NOT NULL,
    IS_DIRECTTRADE TINYINT(1)   NOT NULL,
    CREATEDATE     VARCHAR(255) NOT NULL,
    MODIFYDATE     VARCHAR(255) NOT NULL
);


CREATE TABLE LOCATION
(
    LOCATION_ID       INTEGER PRIMARY KEY auto_increment,
    CITY              VARCHAR(255) NOT NULL,
    CITY_COUNTRY      VARCHAR(255) NOT NULL,
    TOWN              VARCHAR(255) NOT NULL,
    CITY_COUNTRY_TOWN VARCHAR(255) NOT NULL
);

ALTER TABLE POST
    ADD FOREIGN KEY (LOCATION_ID) REFERENCES LOCATION (LOCATION_ID);
