DROP TABLE IF EXISTS POST CASCADE;
DROP TABLE IF EXISTS LOCATION CASCADE;

CREATE TABLE POST
(
    POST_ID        INTEGER PRIMARY KEY AUTO_INCREMENT,
    USER_ID        INTEGER      NOT NULL,
    LOCATION_ID    INTEGER      NOT NULL,
    IMAGE_ID       INTEGER      NOT NULL,
    TITLE          VARCHAR(255) NOT NULL,
    CONTENT        VARCHAR(255) NOT NULL,
    PRICE          VARCHAR(255) NOT NULL,
    IS_NEGOTIABLE  TINYINT(1)   NOT NULL,
    IS_DIRECTTRADE TINYINT(1)   NOT NULL,
    CREATEDATE     DATETIME     NOT NULL,
    MODIFYDATE     DATETIME     NOT NULL
);


CREATE TABLE LOCATION
(
    LOCATION_ID       INTEGER PRIMARY KEY AUTO_INCREMENT,
    CITY              VARCHAR(255) NOT NULL,
    CITY_COUNTRY      VARCHAR(255) NOT NULL,
    TOWN              VARCHAR(255) NOT NULL,
    CITY_COUNTRY_TOWN VARCHAR(255) NOT NULL
);

CREATE TABLE USER
(
    USER_ID      INTEGER PRIMARY KEY AUTO_INCREMENT,
    LOCATION_ID  INTEGER      NOT NULL,
    NICKNAME     VARCHAR(255) NOT NULL,
    PASSWORD     VARCHAR(255) NOT NULL,
    EMAIL        VARCHAR(255) NOT NULL,
    PHONE_NUMBER VARCHAR(255) NOT NULL,
    USER_ROLE    VARCHAR(255) NOT NULL,
    CREATEDATE   DATETIME     NOT NULL,
    MODIFYDATE   DATETIME     NOT NULL
);

ALTER TABLE POST
    ADD FOREIGN KEY (LOCATION_ID) REFERENCES LOCATION (LOCATION_ID);

ALTER TABLE POST
    ADD FOREIGN KEY (USER_ID) REFERENCES USER (USER_ID);

ALTER TABLE USER
    ADD FOREIGN KEY (LOCATION_ID) REFERENCES LOCATION (LOCATION_ID);
